In [1]:

import numpy as np
import pandas as pd

In [ ]:
#Pandas é uma biblioteca que possui 
#códigos abertos e é usada para a análise e 
#manipulação de dados.
#E é uma biblioteca construída sobre Numpy.

In [6]:
# 1. Crie um array NumPy com 10 elementos inteiros aleatórios no intervalo [0, 100]
array1 = np.random.randint(0, 100, 10)
print("Array com valores aleatórios e tipo de dado:")
print(array1)
print("Tipo de dado:", array1.dtype)

# 2. Crie uma matriz de 5x5 com valores aleatórios de [0,1)
matriz = np.random.rand(5, 5)
print("Matriz de 5x5:")
print(matriz)
print("Valor mínimo:", matriz.min())
print("Valor máximo:", matriz.max())
print("Média:", matriz.mean())

# 3. Crie um array com 10 elementos aleatórios no intervalo [0, 1]
array2 = np.random.rand(10)
print("Array com valores aleatórios no intervalo [0, 1]:")
print(array2)

# Crie um novo array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro
array3 = (array2 * 10).astype(int)
print("Novo array com elementos multiplicados por 10 e convertidos para inteiro:")
print(array3)

# 4. Crie um array de duas dimensões com shape (3, 3) e valores aleatórios inteiros no intervalo [0, 9]
array4 = np.random.randint(0, 10, (3, 3))
print("Array de duas dimensões (3x3) com valores aleatórios inteiros:")
print(array4)

# Substitua todos os elementos da segunda linha por -1
array4[-1, :] = -1
print("Array após substituir a segunda linha por -1:")
print(array4)

# 5. Crie um DataFrame com as informações fornecidas
data = {
    'fruta': ["Banana", "Maçã", "Pera"],
    'preco': [7.90, 10.20, 11.80],
    'quantidade': [12, 3, 4]
}

df = pd.DataFrame(data)
print("DataFrame criado:")
print(df)


Array com valores aleatórios e tipo de dado:
[46  4 47 33 47 78  9 20 76 29]
Tipo de dado: int32
Matriz de 5x5:
[[0.09413313 0.11886274 0.03869567 0.86379073 0.32560344]
 [0.28764499 0.70595353 0.40824939 0.31966362 0.68292511]
 [0.86779139 0.27622571 0.65462269 0.16215039 0.07795997]
 [0.16011272 0.83583576 0.83470227 0.01937001 0.4357589 ]
 [0.85323948 0.30567694 0.22387966 0.52787091 0.7024325 ]]
Valor mínimo: 0.019370013638386974
Valor máximo: 0.8677913907615
Média: 0.43132606650103844
Array com valores aleatórios no intervalo [0, 1]:
[0.47539145 0.68625051 0.24609191 0.50519363 0.60442937 0.69633428
 0.24721194 0.62292217 0.03146803 0.99766272]
Novo array com elementos multiplicados por 10 e convertidos para inteiro:
[4 6 2 5 6 6 2 6 0 9]
Array de duas dimensões (3x3) com valores aleatórios inteiros:
[[3 3 9]
 [8 9 9]
 [9 9 2]]
Array após substituir a segunda linha por -1:
[[ 3  3  9]
 [ 8  9  9]
 [-1 -1 -1]]
DataFrame criado:
    fruta  preco  quantidade
0  Banana    7.9         